### ISSUE TITLE
[1pt] Setup the kanban board

### ISSUE THREAD

**Issue by NurkaAmre** [NurkaAmre/ROR-Recipe-App#2]
- **Create the Kanban board**
-  **Add the different project requirements as tasks**
-  **Estimate time needed for each tasks**
-  **Assign tasks to team members**

### Teammates: 2

**Please check out the [Project link](https://github.com/NurkaAmre/ROR-Recipe-App/projects/1) for more information.**

**Comment by Abenezer-Tilahun** [comment]
Hi @NurkaAmre  @Olivier-Kango 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️Good Job for Providing link to your GitHub project
✔️ Good Job for Providing information about the number of people in your group.
✔️Good Job for set up kanban board for  RoR group project


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
